import re
import json

class FieldMapper:
    def __init__(self, candidate, profile, application, resume_path):
        self.candidate = candidate
        self.profile = profile
        self.application = application
        self.resume_path = resume_path
        
        self.answers = {}
        if application and application.application_answers_json:
            self.answers = json.loads(application.application_answers_json)

    def _normalize(self, text):
        return re.sub(r'[^a-z0-9]', '', str(text).lower())

    def resolve_field(self, field_label, field_type, input_id, name_attr, placeholder):
        """
        Returns (value, status)
        Status can be: KNOWN, USER_INPUT_REQUIRED, UNKNOWN_FIELD, UNSAFE_TO_AUTOFILL
        """
        context = f"{field_label} {input_id} {name_attr} {placeholder}".lower()
        
        # Helper to gather possible matches

        # SENSITIVE DEMOGRAPHIC RULES
        sensitive_keywords = [
            "race", "ethnicity", "hispanic", "latino", "gender", "sex", 
            "veteran", "disability", "demographic", "pronouns"
        ]
        if any(kw in context for kw in sensitive_keywords):
            # Do NOT infer. Only allow if explicit per-application answer is provided.
            # However, the rules state: "Never reuse them automatically from another application unless explicitly configured"
            # And: "Always produce: USER_INPUT_REQUIRED unless an explicit per-application answer was deliberately provided"
            # We will just return SENSITIVE_DEMOGRAPHIC to let the browser agent record it properly.
            return None, "SENSITIVE_DEMOGRAPHIC"
            
        matches = []

        if field_type == "file" or "resume" in context or "cv" in context:
            if "resume" in context or "cv" in context or "upload" in context:
                matches.append((self.resume_path, "KNOWN"))
                
        # Name fields
        matched_name = False
        if "first name" in context:
            val = self.candidate.name.split()[0] if self.candidate.name else ""
            matches.append((val, "KNOWN"))
            matched_name = True
        if "last name" in context:
            val = self.candidate.name.split()[-1] if self.candidate.name else ""
            matches.append((val, "KNOWN"))
            matched_name = True
            
        if not matched_name and ("full name" in context or "name" in context):
            matches.append((self.candidate.name, "KNOWN"))
            
        # Contact info
        if "email" in context:
            val = self.profile.default_email or self.candidate.email
            matches.append((val, "KNOWN"))
        if "phone" in context or "mobile" in context:
            val = self.profile.default_phone or self.candidate.phone
            matches.append((val, "KNOWN"))
            
        # Location
        if "location" in context or "city" in context or "address" in context:
            val = self.candidate.location or self.profile.location_preference
            matches.append((val, "KNOWN"))
            
        # Links
        has_url = False
        if "linkedin" in context:
            matches.append(("https://linkedin.com/in/niraj-kumar", "KNOWN"))
            has_url = True
        if "github" in context:
            matches.append(("https://github.com/niraj", "KNOWN"))
            has_url = True
        if "portfolio" in context:
            matches.append(("https://portfolio.com", "KNOWN"))
            has_url = True
            
        if not has_url and "website" in context:
            # Ambiguous website field, multiple possible sources (linkedin, github, portfolio)
            matches.append(("https://linkedin.com/in/niraj-kumar", "KNOWN"))
            matches.append(("https://github.com/niraj", "KNOWN"))
            matches.append(("https://portfolio.com", "KNOWN"))
            
        # Cover letter
        if "cover letter" in context:
            matches.append((self.application.cover_letter, "KNOWN"))
            
        # Profile preferences
        if "notice period" in context or "available" in context:
            matches.append((self.profile.notice_period, "KNOWN"))
        if "work authorization" in context or "work_auth" in context or "sponsorship" in context or "visa" in context:
            matches.append((self.profile.work_authorization, "KNOWN"))
        if "salary" in context or "compensation" in context:
            matches.append((self.profile.salary_expectation, "KNOWN"))
        if "relocate" in context or "relocation" in context:
            matches.append((self.profile.willing_to_relocate, "KNOWN"))
            
        # Application Answers generated by AI
        for q, a in self.answers.items():
            if self._normalize(q) in self._normalize(context) or self._normalize(context) in self._normalize(q):
                if a == "USER_INPUT_REQUIRED":
                    matches.append((None, "USER_INPUT_REQUIRED"))
                else:
                    matches.append((a, "KNOWN"))
                    
        # Dedup matches that have the exact same value (case-insensitive) and status
        unique_matches_map = {}
        for m in matches:
            val, stat = m
            key = str(val).lower().strip() if val else ""
            unique_matches_map[(key, stat)] = m
            
        unique_matches = list(unique_matches_map.values())
        
        if len(unique_matches) == 0:
            return None, "UNKNOWN_FIELD"
        if len(unique_matches) == 1:
            return unique_matches[0]
            
        # If multiple conflicting fields match (e.g. 'first name' vs 'full name' if context is weird)
        return None, "UNSAFE_TO_AUTOFILL"
