"""Initial schema

Revision ID: 627396a1c890
Revises: 38b68f6c55d9
Create Date: 2026-08-19 22:46:03.079906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '627396a1c890'
down_revision: Union[str, Sequence[str], None] = '38b68f6c55d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('projects', sa.Text(), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('preferred_roles', sa.Text(), nullable=True),
    sa.Column('preferred_locations', sa.Text(), nullable=True),
    sa.Column('resume_path', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_id'), 'candidate', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('job_url', sa.String(length=1000), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('salary', sa.String(length=200), nullable=True),
    sa.Column('experience', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('posted_date', sa.String(length=100), nullable=True),
    sa.Column('analysis_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('application_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('notice_period', sa.String(length=200), nullable=True),
    sa.Column('work_authorization', sa.String(length=200), nullable=True),
    sa.Column('location_preference', sa.String(length=200), nullable=True),
    sa.Column('salary_expectation', sa.String(length=200), nullable=True),
    sa.Column('willing_to_relocate', sa.String(length=50), nullable=True),
    sa.Column('default_phone', sa.String(length=50), nullable=True),
    sa.Column('default_email', sa.String(length=150), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id')
    )
    op.create_index(op.f('ix_application_profiles_id'), 'application_profiles', ['id'], unique=False)
    op.create_table('tailored_resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tailored_resumes_id'), 'tailored_resumes', ['id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('tailored_resume_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('application_answers_json', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submission_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('submission_started_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('submission_result', sa.Text(), nullable=True),
    sa.Column('submission_error', sa.Text(), nullable=True),
    sa.Column('submitted_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['tailored_resume_id'], ['tailored_resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_tailored_resumes_id'), table_name='tailored_resumes')
    op.drop_table('tailored_resumes')
    op.drop_index(op.f('ix_application_profiles_id'), table_name='application_profiles')
    op.drop_table('application_profiles')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_candidate_id'), table_name='candidate')
    op.drop_table('candidate')
    # ### end Alembic commands ###
